## Case AMBEV – Planejamento Long Neck Nordeste

### Objetivo
Avaliar os impactos produtivos, logísticos e financeiros do aumento de demanda de MALZBIER BRAHMA (+30% em fevereiro) e crescimento estrutural de +10% no total de Long Neck a partir de março.

A análise buscará responder:

- Devemos seguir com os incentivos comerciais?
- Qual será o plano de produção e transferência?
- Qual o impacto em custo?
- Quais os riscos envolvidos?

### 1. Entendimento da Dor do Cliente

#### VP de Vendas
- Ganhar / manter market share
- Acelerar crescimento premium
- Evitar ruptura
- Proposta: +30% MALZBIER (Fev) e +10% LN (Mar+)

#### VP de Logística
- Capacidade produtiva no limite
- Restrição de envase
- Restrição de líquido (Goose)
- Lead time cabotagem: 25 dias
- Rodoviário: +60% custo e +5% avaria
- DOI mínimo: 12 dias

#### Dor da Companhia
Como crescer premium no Nordeste sem destruir margem ou aumentar risco operacional?

### 2. Limpeza e Estruturação da Base - MAZBIER BRAHMA (Semana W0)
A planilha original possui múltiplos níveis de cabeçalho e estrutura horizontal por semana (W0, W1, W2, W3). 
Considerando que o aumento de demanda proposto no case é específico para o MALZBIER BRAHMA, a análise será iniciada com a estruturação da semana W0 do respectivo produto. 

Para viabilizar a análise, realizamos:

- Seleção das colunas correspondentes à semana W0 e MAZBIER BRAHMA;
- Remoção de colunas vazias decorrentes de células mescladas;
- Padronização dos nomes das variáveis;
- Conversão das colunas numéricas para tipo adequado (object -> float64)

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

In [2]:

file_path = "data/Analise_LongNeck_WSNP - Sem repostas.xlsb"
xls = pd.ExcelFile(file_path, engine="pyxlsb")
xls.sheet_names

['Cenário atual BR',
 'Custos de transferência',
 'Produção PCP',
 'Transferências Programadas',
 'Cenário Divulgado',
 'Cenário com Nova Demanda']

In [9]:
df = pd.read_excel(
    "data/Analise_LongNeck_WSNP - Sem repostas.xlsb",
    sheet_name="Cenário Divulgado",
    engine="pyxlsb",
    header=None
)

# Localizando linhas e colunas refernetes a MALZBIER
df[df.iloc[:,1].astype(str).str.contains("MALZBIER", na=False)]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47
20,70792.00,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,Mapapi,4672.93,NaN,0,NaN,1985.62,2.55,5050.05,0,0,0,2362.74,2.93,NaN,4835.70,NaN,0,NaN,6161.58,0,0,0,3688.62,6.76,NaN,3275.41,0.00,0,NaN,2792.99,0,0,0,3206.21,4.81,NaN,4003.52,NaN,0,NaN,3048.11,0,0,0,2250.79,3.37
40,70792.00,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,SP,4733.75,NaN,7200,NaN,33738.26,42.76,0,-16866.10,0,0,19338.41,18.32,NaN,6332.87,NaN,17280,NaN,0,-10454.80,0,0,19830.74,18.79,NaN,6332.87,NaN,3600,NaN,0,-10454.80,0,0,6643.07,7.38,NaN,5404.18,0.00,13320,NaN,0,-10454.80,0,0,4104.10,4.56

In [ ]:
df_w0 = df.iloc[20:26, 2:15] 

df_w0 = df_w0.dropna(axis=1, how='all')

df_w0.columns = [
    "GEO_REG",
    "Demanda",
    "WSNP",
    "EI",
    "Suf_ini_dias",
    "Transf_Interna",
    "Transf_Cabotagem",
    "Transf_Rodoviario",
    "Transito",
    "EF",
    "Suf_final_dias"
]

df_w0 = df_w0[df_w0["GEO_REG"] != "GEO/REG"]

df_w0

,GEO_REG,Demanda,WSNP,EI,Suf_ini_dias,Transf_Interna,Transf_Cabotagem,Transf_Rodoviario,Transito,EF,Suf_final_dias
20,Mapapi,4672.93,0,1985.62,2.55,5050.05,0,0,0,2362.74,2.93
21,NE Norte,1516.73,16200,302.00,1.19,-9281.17,0,0,0,5704.10,19.64
22,NE Sul,2484.88,0,4383,10.58,3054.15,0,0,0,4952.27,10.98
23,NO Araguaia,60.66,0,0,0,60.66,0,0,0,-0.00,-0.00
24,NO Centro,1713.47,0,964.82,3.38,1116.54,0,0,0,367.88,1.16
25,TOTAL,10448.68,16200,7635.44,4.38,0.22,0,0,0,13386.98,7.14

In [5]:
df_w0.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 20 to 25
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   GEO_REG            6 non-null      str
 1   Demanda            6 non-null      object
 2   WSNP               6 non-null      object
 3   EI                 6 non-null      object
 4   Suf_ini_dias       6 non-null      object
 5   Transf_Interna     6 non-null      object
 6   Transf_Cabotagem   6 non-null      object
 7   Transf_Rodoviario  6 non-null      object
 8   Transito           6 non-null      object
 9   EF                 6 non-null      object
 10  Suf_final_dias     6 non-null      object
dtypes: object(10), str(1)
memory usage: 660.0+ bytes

In [6]:
cols_numericas = df_w0.columns[1:]

for col in cols_numericas:
    df_w0[col] = pd.to_numeric(df_w0[col], errors='coerce')

df_w0.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 20 to 25
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   GEO_REG            6 non-null      str
 1   Demanda            6 non-null      float64
 2   WSNP               6 non-null      int64
 3   EI                 6 non-null      float64
 4   Suf_ini_dias       6 non-null      float64
 5   Transf_Interna     6 non-null      float64
 6   Transf_Cabotagem   6 non-null      int64
 7   Transf_Rodoviario  6 non-null      int64
 8   Transito           6 non-null      int64
 9   EF                 6 non-null      float64
 10  Suf_final_dias     6 non-null      float64
dtypes: float64(6), int64(4), str(1)
memory usage: 660.0 bytes

### 3. Análise de Nível de Serviço (DOI) – Cenário Base (W0)

Conforme premissa do case, o DOI mínimo exigido para a região Nordeste é de 12 dias. Na planilha é calculado a partir de:

DOI = Estoque Final / (Demanda da próxima semana / 6)

Relembrando o conceito de DOI: é o indicador que mostra por quantos dias o estoque atual consegue atender a demanda média, sem receber reposição.

Nesta etapa, analisamos o cenário base (antes do aumento de demanda) para identificar:

- Regiões já abaixo do DOI mínimo -> risco de ruptura; 
- Regiões em zona de risco (próximas de 12 dias);
- Possível fragilidade estrutural do sistema.

In [7]:
df_w0 = df_w0.iloc[0:6]   # pega só as 6 primeiras regiões
df_w0[['GEO_REG', 'Suf_final_dias']]

        GEO_REG  Suf_final_dias
20       Mapapi            2.93
21     NE Norte           19.64
22       NE Sul           10.98
23  NO Araguaia           -0.00
24    NO Centro            1.16
25        TOTAL            7.14

- **DOI Total = 7,14 dias**, significativamente abaixo do mínimo estabelecido;
- Regiões críticas como:
  - Mapapi: 2,93 dias;
  - NO Centro: 1,16 dias;
  - NO Araguaia: 0 dias;
- Apenas NE Norte apresenta nível confortável (19,64 dias), indicando desequilíbrio regional na distribuição de estoque.

Observação: A região do Araguaia possui modelo logístico distinto, com retirada direta pelos revendedores na unidade de Uberlândia., dessa forma, o risco de ruptura nessa região não impacta diretamente a malha logística do Nordeste, devendo ser analisado separadamente.

Esse resultado evidencia que o produto que receberá um aumento de demanda de +30% já opera abaixo do nível mínimo de segurança.

Portanto, antes mesmo da aplicação do incentivo comercial, o sistema já apresenta risco elevado de ruptura, especialmente em determinadas regiões.

### 4. Análise de Aumento de Demanda (+30%) – MALZBIER

O aumento proposto no case prevê um crescimento de +30% na demanda do MALZBIER para fevereiro.

Considerando que o DOI é calculado como:

DOI = Estoque Final / (Demanda da próxima semana / 6)

Temos que o DOI é inversamente proporcional à demanda.  
Logo, mantendo o estoque constante, um aumento de 30% na demanda reduz o DOI aproximadamente na mesma proporção.

Aplicando essa variação ao cenário base:

- DOI Total atual: **7,14 dias**
- DOI estimado com +30%: aproximadamente **4,21 dias**

Regionalmente, a situação torna-se ainda mais crítica:

- Mapapi: cairia de 2,93 para cerca de 0,92 dias;
- NO Centro: cairia de 1,16 para menos de 1 dia;
- Regiões já abaixo do mínimo afastam-se ainda mais do nível de segurança.

Isso indica que, sem ajustes estruturais em produção ou transferências, o aumento de demanda ampliará significativamente o risco de ruptura no Nordeste.

In [8]:
df_novo = pd.read_excel(
    "data/Analise_LongNeck_WSNP - Sem repostas.xlsb",
    sheet_name="Cenário com Nova Demanda",
    engine="pyxlsb",
    header=None
)

df_novo[df_novo.iloc[:,1].astype(str).str.contains("MALZBIER", na=False)]

df_novo = df_novo.iloc[20:26, 2:15]

df_novo = df_novo.dropna(axis=1, how='all')

df_novo.columns = [
    "GEO_REG",
    "Demanda",
    "WSNP",
    "EI",
    "Suf_ini_dias",
    "Transf_Interna",
    "Transf_Cabotagem",
    "Transf_Rodoviario",
    "Transito",
    "EF",
    "Suf_final_dias"
]

df_novo = df_novo[df_novo["GEO_REG"] != "GEO/REG"]

df_novo[['GEO_REG', 'Suf_final_dias']]

        GEO_REG Suf_final_dias
20       Mapapi           0.92
21     NE Norte          13.90
22       NE Sul           7.18
23  NO Araguaia          -1.18
24    NO Centro          -0.36
25        TOTAL           4.21

Conclusão preliminar: no cenário atual, o incentivo comercial não é operacionalmente sustentável sem replanejamento produtivo e logístico.